#!/bin/bash

API_base='http://qun.qq.com/cgi-bin/qun_mgr'

[[ -z $COOKIE || -z $bkn ]] && {
	cat << HELP
qgroup_download is a simple tools writen is BaSH to download QQ groups
informations. 

To use it, you need to set your COOKIE and bkn form qun.qq.com to env, see 
README.md for more informations.

$ export COOKIE=".... your cookie ...." 
$ export bkn="... your bkn ..."
$ $0
HELP

	exit 1
}

[[ ! -d "save" ]] && {
	mkdir save || {
		echo "Err: can't create save dir. "
		exit 1
	}
}

[[ ! -d "save/groups" ]] && {
	mkdir save/groups || {
		echo "Err: can't create save dir for groups. "
		exit 1
	}
}
	

function do_api {
	curl -s -H "Cookie: $COOKIE" "$API_base/$1?bkn=$bkn&$2"
}

# get friends, groups:
echo "[*] fetching friends list, groups list."
do_api get_friend_list > save/friends.json
do_api get_group_list > save/groups.json

# get groups:
target_groups="
$(jq '.join [] .gc' < save/groups.json)
$(jq '.create [] .gc' < save/groups.json)
$(jq '.manage [] .gc' < save/groups.json)"

common_arg="st=0&end=1000&sort=0"

echo "[*] fetching group members."
for group in $target_groups
do
	echo "[*] fetching group id $group."
	do_api search_group_members "gc=$group&$common_arg" > save/groups/$group.json
done

echo "[*] All set. "
